[package]
name = "nix-bindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

[build-dependencies]
bindgen = "0.65.1"
pkg-config = "0.3"
